### ISSUE TITLE
Training on a new dataset

### ISSUE THREAD

**Issue by valeriechen** [metalbubble/TRN-pytorch#12]
How would you set up your input data for process_dataset.py if you wanted to train on your own dataset?

**Comment by Malathi15** [comment]
@valeriechen  I'm also trying to train my own dataset. Did you got the solution can you pls share with me :)

**Comment by Maruidear** [comment]
> @valeriechen 我也在尝试训练自己的数据集。你有没有解决的办法可以和我分享一下:)

Have you solved the problem?
