### ISSUE TITLE
are you have the optical flow for 'something to something'?

### ISSUE THREAD

**Issue by poppingcode** [metalbubble/TRN-pytorch#19]
thanks!!
are you have the optical flow for 'something to something'?

**Comment by tackgeun** [comment]
I guess that optical flow codes in the repository, TSN-pytorch (https://github.com/yjxiong/temporal-segment-networks) are used for calculating the optical flow, because this project is based on TSN-pytorch as the author said. I'm not sure anyway.

**Comment by alexandonian** [comment]
Hi,

We've since released the extracted optical flow for Something-Something-V2 (a superset of the original Something-Something). You can download the data here:
http://relation.csail.mit.edu/data/20bn-something-something-v2-flow.tar.gz

**Comment by tackgeun** [comment]
Thank you for explanations!

**Comment by gamzeakyol** [comment]
Hi, 
Have you any pretrained model with optical flow? 
Thanks

**Comment by poppingcode** [comment]
> optical flow

 I haven't done it for more than half a year,maybe it was delete . it is suggest that you make optical flow data first,then train it in you model

**Comment by gamzeakyol** [comment]
Thank you, maybe I will try it

**Comment by mangdian** [comment]
@alexandonian  do you have optical flow images of something-something-v1? Thanks

**Comment by alexandonian** [comment]
Hi all,

I am fairly certain that something-something-v1 is a subset of
something-something-v2, which means that the released data also contain all
of the optic flow images associated with something-something-v1. I can look
to see if we still have the something-something-v1 files separately, but if
you need them right away, the quickest thing to do would be to filter out
the v1 images by name.

-Alex

**Comment by mangdian** [comment]
@alexandonian  It is difficult to filter out the V1 images by name, because there is no correlation between the names of videos or categories in these two version.

**Comment by alexandonian** [comment]
Ahh, ok. I am preparing the files now and will upload shortly.

**Comment by mangdian** [comment]
@alexandonian Thank you so much

**Comment by alexandonian** [comment]
Hi, you should be able to download something-something-v1 optic flow here:
http://relation.csail.mit.edu/data/20bn-something-something-v1-flow.tar.gz

-Alex
