### ISSUE TITLE
Data prep for Moments in Time or AVA datasets

### ISSUE THREAD

**Issue by sophia-wright-blue** [metalbubble/TRN-pytorch#25]
Thank you for releasing the code. The data preparation guidelines and scripts are especially helpful. Could you point me to similar guidelines/scripts/repos to process the Moments in Time or AVA datasets?

 (so scripts similar to
https://github.com/metalbubble/TRN-pytorch/blob/master/process_dataset.py , https://github.com/metalbubble/TRN-pytorch/blob/master/datasets_video.py and https://github.com/metalbubble/TRN-pytorch/blob/master/extract_frames.py
 for the Moments in Time or AVA datasets?)

Thank you again for the setting up this repo,

**Comment by Mikcal** [comment]
Did you solve it?

**Comment by sophia-wright-blue** [comment]
Hi @Mikcal , I had to move on to another project, hope you're able to find a good solution, good luck!
