### ISSUE TITLE
process_dataset.py of Charades for action recognition

### ISSUE THREAD

**Issue by sjkai** [metalbubble/TRN-pytorch#5]
Firstly, thank you so much for your excellent code and paper.

I'm trying to adopt TRN for action recognition with Charades Dataset (Charades_v1). However, the data preprocessing of Charades_v1 seems not as easy as something-something because there are multi-class labels in one video.
```
- actions:  
Semicolon-separated list of "class start end" triplets for each actions in the video, such as c092 11.90 21.20;c147 0.00 12.60
```
Should I divide one video into serveral segments?
Could you please provide the `process_dataset.py` of Charades you used for action recognition which can be adopted to generate the index files for train, val, and test split (charades/category.txt,charades/train_segments.txt and charades/test_segments.txt).

Thank you.

**Comment by metalbubble** [comment]
https://github.com/metalbubble/TRN-pytorch/blob/master/process_dataset_charades.py
