### ISSUE TITLE
how to use the something-to-something dataset for your model.

### ISSUE THREAD

**Issue by poppingcode** [metalbubble/TRN-pytorch#6]
i have download the something-to-something dataset from “https://www.twentybn.com/datasets/something-something” and four files which is train.csv-validation.csv-test.csv-labels.csv .
but i don't how to use it(RGB pictures) ,can you give me some example?
i hope know more details.
thanks~

**Comment by metalbubble** [comment]
https://github.com/metalbubble/TRN-pytorch/blob/master/process_dataset.py

**Comment by BinqingWu** [comment]
Could you please tell me where to download .csv files? Thank you.

**Comment by sampathchanda** [comment]
@metalbubble Could you please clarify where to download the .csv files (validation, test and labels)?
